# Generated by Django 3.2.16 on 2022-12-23 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221221_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.001, 'Ингредиента должно быть не менее0.001 <django.db.models.query_utils.DeferredAttribute object at 0x000001F5C9950E08>')], verbose_name='Количество ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления должно быть не менее 1 минуты')], verbose_name='Время приготовления, мин.'),
        ),
    ]
