# Generated by Django 3.2.16 on 2022-12-23 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221223_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.001, 'Ингредиента должно быть не менее0.001 <django.db.models.query_utils.DeferredAttribute object at 0x0000022089CD1E88>')], verbose_name='Количество ингредиента'),
        ),
    ]
