# Generated by Django 3.2.16 on 2022-12-23 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredientsinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.001, 'Ингредиента должно быть не менее0.001 <django.db.models.query_utils.DeferredAttribute object at 0x000002A61136FF48>')], verbose_name='Количество ингредиента'),
        ),
    ]
