# Generated by Django 3.2.16 on 2022-12-23 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_ingredientsinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='amount',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.001, message='Ингредиента должно быть >= 0.001.')], verbose_name='Количество ингредиента'),
        ),
    ]
