# Generated by Django 3.2.16 on 2022-12-23 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_ingredientsinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='amount',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.001, message='Ингредиента должно быть не менее 0.001.')], verbose_name='Количество ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления должно быть не менее 1 минуты!')], verbose_name='Время приготовления, мин.'),
        ),
    ]
