# Generated by Django 3.2.16 on 2022-12-23 09:51

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221223_1246'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_not_user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('author__exact', django.db.models.expressions.F('user'))), name='author_not_user'),
        ),
    ]
